language: java

jdk:
  - oraclejdk8

install: true # don't run `gradle assemble` https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
script: gradle check # don't use the `gradlew` wrapper
