language: java

jdk:
  - oraclejdk8

# don't run `gradle assemble` https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true
script: ./gradlew check

before_cache:
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle

env:
  global:
    - secure: "RiD3yO4Nu+NzMaa+7UNbPr7bidL2MQNIsxE/wzqGtg5D1M81q8Kkug23Ye7F5vIjvlVgsAwFb977nm+diHqgWG76VGhvFX5V2YyzfpYKbnKHnw8ftPOEVwZZhBGzER6ImlWEU+5Ju8+w61K+LNyLhn1cmtEb+i3PWfJ5Lm1I6GY4ME/qY6vyXC0dQEHBqsRHXyfn/EJPAx2FwrX5K7yaxPiyAILiEQblV+wr7fWUskiGzDLpMS2bP9sNmUA/vaalxIgPaJn2uUxUh2C8uek+06Fm4kdtc4Mh3Y1PurDsAPs99krIPw/of3ywLi2kMFgU+UaXcj06EThZgXE/HJzjRrVCbiH2g/KTXfNuhZXUB6EkYxNHpVuXjnvsoowscquKFspEnvsceOlFJlG9gc2cBSyAWlLTHiebiCTccxenPuc0Jpmr1dh6PGhyalc1Z4Z1Wb0M6JUhzfOG7L2dWhKeEu8hM2dgih3tEYbAqb1fSZ16Wtbt/TCtXMVnnEbR9w2o6YOjDDhQsOxrBxqUinYKwf4UeqsvKGJ8MwhAGPGYwO+0XzuxESeFgi9CUwcwbZRkE8jTRG7/Dev7RE07UFCgmuNpTWAqU5BtJLuqUH0do8g7JLwFs9GTkp/WCb59SMcHeIh5EeYFng2XZBIuB3j9cbgm6XdQAU/kZ+3gHNtpj5w="
    - secure: "o0W61FL6toGf8+ztT19AD+tFvhVnaBC1UzVafW8eQpkcJXqnmVizieso1DJI/M13i6cUh1zTg+NZwj2Bee89O41Jp/txOVW/SLnVRANnC6kUa6dHVU8k+boxUbNrjeCkNPrWZ5YsxdfY3y1Ybp4qusOYqOdZw5dY2uOgaBFJzf/bn8IY6Moust2KLKZu84uyba2x4V0zq1HaMuu47Di+kfZZkZOLNLyiyZFp5SlslMToZVdtXaCMqJpelCLHsBAnt8wRSNw7D31qQDEShHpmziPdVORdfEXUaqcMTdBUHWDt27Y618JSV5ngg+V1ZSv+tIFsYF/ei+26MPEFLS2oiaeCl1jHRw8shIf8y/oG3l+yd7Tgz1K6V+ZLLcqS4N3BcjWqrfkEWgchqHJImRYw2/sGS1MfTAcVREyLhu6cObIhW31fpg7UVGk0vKN610veNLZ5Qe3Yjb3LStbhGPp1Vqz1DpgZB1TpUtxZdjCJfyp/Ky9lgvH4N3k7VFSG1iSBPexZFtTzW/r1u6MELxW9/lVhF4mmgvi7ljbOwbKtsLqARcJePnPa4vSZwAK7WmWm2xX8g8ds8a2w08JkZYqnAsc+/i7wMOEUNF6pYDXKg452ClOfNaPed8L5NYEbMYzwbJcjZ+zimhWAKYjNwtReMhGdARn8U4fkQMv/wZhoFMQ="

after_success: ./gradlew -PpublishUsername=${SONATYPE_USERNAME} -PpublishPassword=${SONATYPE_PASSWORD} uploadArchives
  