language: java

jdk:
  - openjdk11

# don't run `gradle assemble` https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      env:
        - ORG_GRADLE_PROJECT_servletContainer=tomcat
        - ORG_GRADLE_PROJECT_fips=false
      script:
        - ./gradlew dependencies
        - ./gradlew check
    - stage: test
      env:
        - ORG_GRADLE_PROJECT_servletContainer=tomcat
        - ORG_GRADLE_PROJECT_fips=true
      script:
        - ./gradlew dependencies
        - ./gradlew check
    - stage: test
      env:
        - ORG_GRADLE_PROJECT_servletContainer=jetty
        - ORG_GRADLE_PROJECT_fips=false
      script:
        - ./gradlew dependencies
        - ./gradlew check
    - stage: test
      env:
        - ORG_GRADLE_PROJECT_servletContainer=jetty
        - ORG_GRADLE_PROJECT_fips=true
      script:
        - ./gradlew dependencies
        - ./gradlew check
    - stage: test
      env:
        - ORG_GRADLE_PROJECT_servletContainer=undertow
        - ORG_GRADLE_PROJECT_fips=false
      script:
        - ./gradlew dependencies
        - ./gradlew check
    - stage: test
      env:
        - ORG_GRADLE_PROJECT_servletContainer=undertow
        - ORG_GRADLE_PROJECT_fips=true
      script:
        - ./gradlew dependencies
        - ./gradlew check
    - stage: deploy
      env:
        - ORG_GRADLE_PROJECT_servletContainer=tomcat
        - ORG_GRADLE_PROJECT_fips=true
      script:
        - ./gradlew dependencies
        - |
          ./gradlew \
            -Dorg.gradle.internal.publish.checksums.insecure=true \
            -PnexusUsername=${SONATYPE_USERNAME} \
            -PnexusPassword=${SONATYPE_PASSWORD} \
            -Psigning.keyId=${GPG_KEY_ID} \
            -Psigning.password=${GPG_KEY_PASSWORD} \
            -Psigning.secretKeyRingFile=secring.gpg \
            --stacktrace --info \
            myPublish

before_cache:
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/daemon/

cache:
  directories:
  - $HOME/.gradle

before_install:
  - env | grep '^TRAVIS_' | sort
  - openssl aes-256-cbc -K $encrypted_7a85652b67b9_key -iv $encrypted_7a85652b67b9_iv
    -in secring.gpg.enc -out secring.gpg -d

env:
  global:
    - GPG_KEY_ID: B17E37F8
    - SONATYPE_USERNAME: dtreskunov
    - secure: "IVoDVL/4fv5QoN2xKb4mSDsxM2HkNYTAYw4BW2z6WW9i77PGSGmnBqA4Mop0JzwfhyYw5zsDVDLP6h81UBHRTVgbfasAGwRl6aorsmAV0K9UF6m18mEyk41XtK23GnQX0ECARyYdlQdYTozpuK6BD4YwINPcwUGrGoA6zxe85ayLJncUfpRjemSlWm0t5QbdemGtx0jtrK0V1Ns8KkPfUeGIZRO9CS+TRTkDePLcOR3l4yhM+SP33XRLi3GfEhLhMPmtyUGf0l1IDQT9AcuC9R0YI2eijP+H/jha5U4gd+ytrgo6W6VBx/tFG5fe57jAq06fNzHaKW5YWIiRM38q6/jvk766SIx9tbjVxyiwA+XoWYpsd9BMrH4eH8RX+tYgSl5m/jUxfwTIxzxVyiB6g3sX9Z7asKUCho3ur67RAEOMiu7RvEpaWf3Xe0pppnfSHO9M1DYHg4bstD38u/IVHqsBg99LhzKZaodd07pE+CYk4tgKeUNp2n9AN12JHa6kQxCvljRlrXxhqrZn7oDvaBRhFU212Gj52JYtATYh9bPhE522LegypUR6S+NBc0BATfaOii320oNB1Cp7Ua1BOsxbmwsZ3Uyhth1v4VKKrz/rJLrVpB+fsdOC/JyQ0HJWq4PZ4YmZ7JadSfT5QrzscvZ0h9DSvad9Ce5eNc6fq/0=" # GPG_KEY_PASSWORD
    - secure: "wqrO3OtycdrV6t2IkqdlTyx8T/2LPEjrJddwGO5MIqE7YuLyeUqGokbi74zQtu75J4UQM1VNGU4XzXaVRArkYBEt7I2hL51sPRCq+/0xzw5d+vgKrjisTyRVm5QEvw7z8iaGUKu3bh6cyhPhSAZjkaTMtkjLffgAMxpvUWHH+uxA1zFF9XECzkhdUHyIu7lm4HZbxBVr8e/w5uClQE149tDd84l8Zn6xPXzdj/N7tcNVb2jNygbNJE8oAuImC2rPLESdT/GCIw4Z9elFaWNyHuFguHXuZApPMjLYBwaQ+Yy+qgLe8xkHtIvN82HiD5XJa/TTAWKJyR00BQP7X+1oBb1JR6pT5KK4b267Ad1CSdqNY8jcOG+QTNY/I67p0X5zvA2Vrt67sHVGRZDcTePfKZCSJNcwphjut7M310rM2pMPay0EI1shTVuAX9nJgrAfZoJw3Op6Q1ZOVeQDyKwesHEISBf65LOrLckXEA7/zw+qC0lGMhSDqY2Jq4FOjNNdeyMnNCfh0Fpz1bR/bDYEfhOfS7kefbSow3bhi+si8aE3CkQvZbiMx4x/97Nfde7LdUL73ah/tUHWTJdRUMn0nmKPEIpix4Ape9Dj5LKgfvEQB3SX9swgfMI0Xlfyc4mZ8/ZwN0MGsCccRlXBdQh5vklc7ZPJmp3D3+dFxIpWnXU=" # SONATYPE_PASSWORD


